### ISSUE TITLE
Daemon does not gracefully handle programs that crash on startup

### ISSUE THREAD

**Issue by maihde** [LGSInnovations/bits#15]
When using the Daemon helper, if a program crashes on startup the handlers in _onClose() do not gracefully deal with the issue.

```
 error: Uncaught exception in module my-module: Uncaught, unspecified "error" event. (Process crashed with code null. Restarting...)
 Error: Uncaught, unspecified "error" event. (Process crashed with code null. Restarting...)
    at Daemon.emit (events.js:163:17)
    at Daemon._onClose (bits/lib/helpers/daemon.js:130:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
2017-09-29T19:37:04.038Z - error: Module my-module died cleaning up now
```

This is because EventEmitter handles 'error' with special logic that causes the program to terminate if no listeners are connected.

I suggest that either: (A) the Daemon class register an error handler against itself or (B) the README.md documentation is expanded to show 

```
daemon.on('error', (err) => {}); // if you don't register an error handler, if the Daemon dies it will crash your module.
```

**Comment by nbroeking** [comment]
@KevinDyer @bschmickley @mokus0 @nanpx 

I like having the daemon module add an error handler and then allowing the outside add its own if necessary?

**Comment by nanpx** [comment]
The bits-daemon now handles the daemon process. It has the ability to emit an error event by which a listener could call the kill method. See https://github.com/LGSInnovations/node-bits-daemon/blob/master/src/daemon.js
