### ISSUE TITLE
Default configuration should not allow system restart/shutdown

### ISSUE THREAD

**Issue by maihde** [LGSInnovations/bits#31]
The default BITS configuration allows a user to execute 'restart' or 'shutdown' from the web page.  While appropriate for some situations, this should be an opt-in behavior instead of the default.

**Comment by nbroeking** [comment]
This is actually very high on my priority list. The idea would be to pull out that toolbar item into a different module. Thoughts?

**Comment by Sha-Bang** [comment]
I think power control as a module makes a lot of sense, especially if we want to support architectures that use something other than reboot now

**Comment by nanpx** [comment]
This has now been pulled out of base
