### ISSUE TITLE
Add capability to send event from base-message-center element

### ISSUE THREAD

**Issue by MidnightJava** [LGSInnovations/bits#32]
The `BaseMessageCenterBehavior` implementation for the `base-message-center` custom element does not provide a `sendEvent` function. It would be useful to be able to send events to the server-side message-center from the client.

**Comment by nanpx** [comment]
The bits-socket.io-client has the ability to send events. However, the polymer behavior does not implement it. This can easily be done in your own component though.

See https://github.com/LGSInnovations/node-bits-socket.io-client/blob/master/index.js
